### ISSUE TITLE
Subtlety: Consider adding descriptions to sections of the CSS code.

### ISSUE THREAD

**Issue by josephtkim** [tehreilly/TeaCozy#4]
Similar to the HTML code, consider adding descriptions to sections of the CSS code. This will make it easier to understand which sections of the page the properties are being applied. For instance,

```css
/* Contact Section */
#contact {
  height: 200px;
}

/* Footer Section */
footer {
    text-align: left;
    padding-left: 20px;
}
```
